# Generated by Django 5.1.2 on 2024-12-02 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_account_password_account_encrypted_password_and_more'),
        ('api', '0006_remove_emailotpdevice_confirmed_and_more'),
    ]

    operations = [
    ]
